# Generated by Django 4.1.7 on 2024-01-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='randomquestionmarks',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.classes'),
        ),
        migrations.AddField(
            model_name='randomquestionmarks',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.classes'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='courseclasstime',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.classes'),
        ),
        migrations.AddField(
            model_name='courseclasstime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
    ]
