# Generated by Django 4.1.7 on 2023-10-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomquestionmarks',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
