# Generated by Django 4.1.7 on 2023-10-01 07:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
