# Generated by Django 4.1.7 on 2023-10-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
