# Generated by Django 4.1.7 on 2024-01-04 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_courseclasstime_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclasstime',
            name='times',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
